[colors.primary]
background = "#282828"
foreground = "#ebdbb2"
dim_foreground = "#ebdbb2"
bright_foreground = "#fbf1c7"

[colors.cursor]
text = "#282828"
cursor = "#ebdbb2"

[colors.vi_mode_cursor]
text = "#282828"
cursor = "#83a598"

[colors.search.matches]
foreground = "#282828"
background = "#d79921"

[colors.search.focused_match]
foreground = "#282828"
background = "#b8bb26"

[colors.footer_bar]
foreground = "#282828"
background = "#d79921"

[colors.hints.start]
foreground = "#282828"
background = "#fabd2f"

[colors.hints.end]
foreground = "#282828"
background = "#d79921"

[colors.selection]
text = "#282828"
background = "#ebdbb2"

[colors.normal]
black = "#282828"       # Ansi 0
red = "#cc241d"         # Ansi 1
green = "#98971a"       # Ansi 2
yellow = "#d79921"      # Ansi 3
blue = "#458588"        # Ansi 4
magenta = "#b16286"     # Ansi 5
cyan = "#689d6a"        # Ansi 6
white = "#a89984"       # Ansi 7

[colors.bright]
black = "#928374"       # Ansi 8
red = "#fb4934"         # Ansi 9
green = "#b8bb26"       # Ansi 10
yellow = "#fabd2f"      # Ansi 11
blue = "#83a598"        # Ansi 12
magenta = "#d3869b"     # Ansi 13
cyan = "#8ec07c"        # Ansi 14
white = "#ebdbb2"       # Ansi 15

[colors.dim]
black = "#1d2021"
red = "#9d0006"
green = "#79740e"
yellow = "#b57614"
blue = "#076678"
magenta = "#8f3f71"
cyan = "#427b58"
white = "#928374"

[[colors.indexed_colors]]
index = 16
color = "#fe8019"       # Orange

[[colors.indexed_colors]]
index = 17
color = "#d65d0e"       # Bright orange

